server:
  port: 9007
spring:
  application:
    name: documentation-service
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
