// Generates the Kubernetes manifests from one table of services.
//
//   node infrastructure/kubernetes/generate.cjs
//
// The hand-written manifests had drifted from the stack that actually runs: one shared database,
// no JWT key or service URLs wired in, one shared Kafka identity, config-server and Eureka
// addresses nothing reads. The same mistakes the compose file had before CI started running it.
// Generating every Deployment from one table keeps ten services from drifting apart again, and
// the shared pieces - the database init script, the Kafka ACL script, the Prometheus and Grafana
// configuration - are read from the files compose uses, so there is one copy of each.
//
// CI applies the output to a real cluster (kind) and checks it; see the "kubernetes" job.
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..");
const OUT = __dirname;
const NS = "devforge-ai";
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");

// name, port, database (null: none), kafka identity (null: no Kafka client), extra env.
const SERVICES = [
  { name: "auth-service", port: 9001, db: "devforge_auth", kafka: true, env: [
    ["REDIS_HOST", "redis"], ["REDIS_PORT", "6379"],
    ["MAIL_HOST", { configMapKeyRef: "MAIL_HOST" }], ["MAIL_PORT", { configMapKeyRef: "MAIL_PORT" }],
    ["MAIL_AUTH_ENABLED", { configMapKeyRef: "MAIL_AUTH_ENABLED" }],
    ["MAIL_STARTTLS_ENABLED", { configMapKeyRef: "MAIL_STARTTLS_ENABLED" }],
    ["DEVFORGE_APP_BASE_URL", { configMapKeyRef: "DEVFORGE_APP_BASE_URL" }],
    ["DEVFORGE_COOKIE_SECURE", { configMapKeyRef: "DEVFORGE_COOKIE_SECURE" }],
    ["DEVFORGE_COOKIE_SAME_SITE", { configMapKeyRef: "DEVFORGE_COOKIE_SAME_SITE" }],
    ["DEVFORGE_REQUIRE_EMAIL_VERIFICATION", { configMapKeyRef: "DEVFORGE_REQUIRE_EMAIL_VERIFICATION" }],
    ["MAIL_USERNAME", { secret: "mail-username" }], ["MAIL_PASSWORD", { secret: "mail-password" }],
  ] },
  { name: "project-service", port: 9002, db: "devforge_project", kafka: true },
  { name: "task-service", port: 9003, db: "devforge_task", kafka: true },
  { name: "git-service", port: 9005, db: "devforge_git", kafka: true, volume: "/app/data/git-repositories" },
  { name: "review-service", port: 9006, db: "devforge_review", kafka: true },
  { name: "documentation-service", port: 9007, db: "devforge_documentation", kafka: true },
  { name: "chat-service", port: 9008, db: "devforge_chat", kafka: true },
  { name: "analytics-service", port: 9010, db: "devforge_analytics", kafka: true },
  { name: "notification-service", port: 9011, db: "devforge_notification", kafka: true },
];
const GATEWAY_ROUTES = {
  AUTH_SERVICE_URL: "auth-service:9001", PROJECT_SERVICE_URL: "project-service:9002",
  TASK_SERVICE_URL: "task-service:9003", GIT_SERVICE_URL: "git-service:9005",
  REVIEW_SERVICE_URL: "review-service:9006", DOCUMENTATION_SERVICE_URL: "documentation-service:9007",
  CHAT_SERVICE_URL: "chat-service:9008", ANALYTICS_SERVICE_URL: "analytics-service:9010",
  NOTIFICATION_SERVICE_URL: "notification-service:9011",
};

// ---------------------------------------------------------------- YAML helpers

const q = (s) => JSON.stringify(String(s)); // JSON strings are valid YAML scalars
const indent = (text, n) => text.split("\n").map((l) => (l ? " ".repeat(n) + l : l)).join("\n");
const literal = (text, n) => "|\n" + indent(text.replace(/\s+$/, ""), n);

function envVar([name, value]) {
  if (typeof value === "string") return `- name: ${name}\n  value: ${q(value)}`;
  if (value.configMapKeyRef) {
    return `- name: ${name}\n  valueFrom:\n    configMapKeyRef:\n      name: devforge-ai-config\n      key: ${value.configMapKeyRef}`;
  }
  return `- name: ${name}\n  valueFrom:\n    secretKeyRef:\n      name: devforge-ai-secrets\n      key: ${value.secret}`;
}

const header = (name) =>
  `# GENERATED by infrastructure/kubernetes/generate.cjs - edit the generator, not this file.\n# ${name}\n`;

// ---------------------------------------------------------------- application services

function deployment(svc) {
  const env = [
    ["SPRING_PROFILES_ACTIVE", { configMapKeyRef: "SPRING_PROFILES_ACTIVE" }],
    ["DEVFORGE_JWT_ISSUER", { configMapKeyRef: "DEVFORGE_JWT_ISSUER" }],
    ["DEVFORGE_JWT_SIGNING_KEY", { secret: "jwt-signing-key" }],
    ["DEVFORGE_METRICS_TOKEN", { secret: "metrics-token" }],
    ["PROJECT_SERVICE_URL", "http://project-service:9002"],
    ["GIT_SERVICE_URL", "http://git-service:9005"],
  ];
  if (svc.db) {
    env.push(
      ["DEVFORGE_DB_URL", `jdbc:postgresql://postgres:5432/${svc.db}`],
      ["POSTGRES_USER", { secret: "postgres-username" }],
      ["POSTGRES_PASSWORD", { secret: "postgres-password" }]);
  }
  if (svc.kafka) {
    env.push(
      ["KAFKA_BOOTSTRAP_SERVERS", "kafka:29092"],
      ["DEVFORGE_KAFKA_REQUIRE_AUTHENTICATION", "true"],
      ["DEVFORGE_KAFKA_SECURITY_PROTOCOL", { configMapKeyRef: "DEVFORGE_KAFKA_SECURITY_PROTOCOL" }],
      ["DEVFORGE_KAFKA_SASL_MECHANISM", { configMapKeyRef: "DEVFORGE_KAFKA_SASL_MECHANISM" }],
      ["DEVFORGE_KAFKA_SASL_USERNAME", svc.name],
      ["DEVFORGE_KAFKA_SASL_PASSWORD", { secret: `kafka-password-${svc.name}` }]);
  }
  for (const e of svc.env ?? []) env.push(e);

  const volumeMounts = svc.volume
    ? `\n          volumeMounts:\n            - name: data\n              mountPath: ${svc.volume}`
    : "";
  const volumes = svc.volume
    ? `\n      volumes:\n        - name: data\n          persistentVolumeClaim:\n            claimName: ${svc.name}-data`
    : "";
  const pvc = svc.volume
    ? `---\napiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: ${svc.name}-data\n  namespace: ${NS}\nspec:\n  accessModes: [ReadWriteOnce]\n  resources:\n    requests:\n      storage: 2Gi\n`
    : "";

  return `---
apiVersion: v1
kind: Service
metadata:
  name: ${svc.name}
  namespace: ${NS}
spec:
  selector:
    app: ${svc.name}
  ports:
    - port: ${svc.port}
      targetPort: ${svc.port}
${pvc}---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${svc.name}
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${svc.name}
  template:
    metadata:
      labels:
        app: ${svc.name}
    spec:
      containers:
        - name: ${svc.name}
          image: devforge-ai/${svc.name}:latest
          # Built and loaded into the cluster rather than pulled; a registry deployment would
          # set a real tag and Always.
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${svc.port}
          env:
${indent(env.map(envVar).join("\n"), 12)}
          # Startup is slow (JVM, Flyway); readiness gates traffic, liveness restarts a stuck pod.
          startupProbe:
            httpGet: { path: /actuator/health, port: ${svc.port} }
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet: { path: /actuator/health, port: ${svc.port} }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: ${svc.port} }
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests: { cpu: 50m, memory: 384Mi }
            limits: { memory: 768Mi }
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }${volumeMounts}${volumes}
`;
}

function gateway() {
  const env = [
    ["SPRING_PROFILES_ACTIVE", { configMapKeyRef: "SPRING_PROFILES_ACTIVE" }],
    ["DEVFORGE_METRICS_TOKEN", { secret: "metrics-token" }],
    ["DEVFORGE_CORS_ORIGINS", { configMapKeyRef: "DEVFORGE_APP_BASE_URL" }],
    ["DEVFORGE_RATE_LIMIT_AUTH_PER_MINUTE", { configMapKeyRef: "DEVFORGE_RATE_LIMIT_AUTH_PER_MINUTE" }],
    ...Object.entries(GATEWAY_ROUTES).map(([k, v]) => [k, `http://${v}`]),
  ];
  return deployment({ name: "api-gateway", port: 8080 })
    .replace(/          env:\n[\s\S]*?\n          # Startup/, `          env:\n${indent(env.map(envVar).join("\n"), 12)}\n          # Startup`);
}

function frontend() {
  return `---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ${NS}
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: devforge-ai/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # nginx proxies /api here, so the browser stays on one origin for the session cookies.
            - name: API_GATEWAY_UPSTREAM
              value: "http://api-gateway:8080"
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            periodSeconds: 10
          resources:
            requests: { cpu: 20m, memory: 32Mi }
            limits: { memory: 128Mi }
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }
`;
}

// ---------------------------------------------------------------- infrastructure

function kafkaJaas() {
  // Built from the secret at start: Kubernetes expands $(VAR) references to earlier env vars.
  const users = ["user_admin=\"$(KAFKA_ADMIN_PASSWORD)\""].concat(
    SERVICES.filter((s) => s.kafka).map((s) => `user_${s.name}="$(KAFKA_PASSWORD_${s.name.replace(/-/g, "_").toUpperCase()})"`));
  return `org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="$(KAFKA_ADMIN_PASSWORD)" ${users.join(" ")};`;
}

function infrastructure() {
  const kafkaSecretEnv = [["KAFKA_ADMIN_PASSWORD", { secret: "kafka-admin-password" }]].concat(
    SERVICES.filter((s) => s.kafka).map((s) => [
      `KAFKA_PASSWORD_${s.name.replace(/-/g, "_").toUpperCase()}`, { secret: `kafka-password-${s.name}` }]));

  return `---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ${NS}
data:
  # The same script compose runs: one database per service.
  01-databases.sql: ${literal(read("infrastructure/docker/postgres/01-databases.sql"), 4)}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ${NS}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ${NS}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
${indent([["POSTGRES_USER", { secret: "postgres-username" }], ["POSTGRES_PASSWORD", { secret: "postgres-password" }], ["POSTGRES_DB", "devforge"], ["PGDATA", "/var/lib/postgresql/data/pgdata"]].map(envVar).join("\n"), 12)}
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \\"$POSTGRES_USER\\""]
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ${NS}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ${NS}
spec:
  selector:
    app: kafka
  ports:
    - port: 29092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: ${NS}
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # The Confluent image turns every KAFKA_* variable into a broker setting, including the
      # service links Kubernetes injects for the "kafka" Service; those must not be set.
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.7.1
          ports:
            - containerPort: 29092
          env:
${indent(kafkaSecretEnv.map(envVar).join("\n"), 12)}
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            # The unauthenticated controller listener stays on the pod's loopback, as in compose.
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:29093"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:29092,CONTROLLER://localhost:29093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: "PLAIN"
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: "PLAIN"
            - name: KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG
              value: ${q(kafkaJaas())}
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              value: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: "false"
            - name: KAFKA_SUPER_USERS
              value: "User:admin;User:ANONYMOUS"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"
            - name: CLUSTER_ID
              value: "devforge-kube-cluster1"
          readinessProbe:
            tcpSocket: { port: 29092 }
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-setup
  namespace: ${NS}
data:
  # The same script compose runs: topics, and each service's grants.
  setup.sh: ${literal(read("infrastructure/docker/kafka/setup.sh"), 4)}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-setup
  namespace: ${NS}
spec:
  backoffLimit: 20
  template:
    spec:
      restartPolicy: OnFailure
      enableServiceLinks: false
      containers:
        - name: kafka-setup
          image: confluentinc/cp-kafka:7.7.1
          command: ["sh", "/setup/setup.sh"]
          env:
${indent(envVar(["KAFKA_ADMIN_PASSWORD", { secret: "kafka-admin-password" }]), 12)}
          volumeMounts:
            - name: setup
              mountPath: /setup
      volumes:
        - name: setup
          configMap:
            name: kafka-setup
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: ${NS}
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
    - name: web
      port: 8025
---
# Captures mail instead of delivering it. Replace with a real SMTP relay (MAIL_HOST in the
# ConfigMap) for anything but a test cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: ghcr.io/axllent/mailpit:v1.31.4
          ports:
            - containerPort: 1025
            - containerPort: 8025
`;
}

function monitoring() {
  return `---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ${NS}
data:
  # The compose file with the development password swapped for the token from the Secret.
  prometheus.yml: ${literal(read("infrastructure/monitoring/prometheus.yml")
    .replace("password: metrics-dev-only", "password_file: /etc/prometheus-secret/metrics-token"), 4)}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ${NS}
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v3.15.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: scrape-token
              mountPath: /etc/prometheus-secret
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: scrape-token
          secret:
            secretName: devforge-ai-secrets
            items:
              - key: metrics-token
                path: metrics-token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: ${NS}
data:
  datasource.yml: ${literal(read("infrastructure/monitoring/grafana/provisioning/datasources/prometheus.yml"), 4)}
  dashboards.yml: ${literal(read("infrastructure/monitoring/grafana/provisioning/dashboards/devforge.yml"), 4)}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: ${NS}
data:
  devforge-services.json: ${literal(read("infrastructure/monitoring/grafana/dashboards/devforge-services.json"), 4)}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ${NS}
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:13.2.3
          ports:
            - containerPort: 3000
          env:
${indent([["GF_SECURITY_ADMIN_PASSWORD", { secret: "grafana-admin-password" }]].map(envVar).join("\n"), 12)}
          volumeMounts:
            - name: provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
            - name: provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: provisioning
          configMap:
            name: grafana-provisioning
        - name: dashboards
          configMap:
            name: grafana-dashboards
`;
}

// ---------------------------------------------------------------- write

const write = (file, title, body) => fs.writeFileSync(path.join(OUT, file), header(title) + body);
write("infrastructure.yaml", "PostgreSQL, Redis, Kafka with per-service ACLs, Mailpit", infrastructure());
write("services.yaml", "The gateway, the services and the frontend",
  [gateway(), ...SERVICES.map(deployment), frontend()].join(""));
write("monitoring.yaml", "Prometheus and Grafana, provisioned from the compose stack's files", monitoring());
console.log("wrote infrastructure.yaml, services.yaml, monitoring.yaml");
