apiVersion: v1
kind: Secret
metadata:
  name: devforge-ai-secrets
  namespace: devforge-ai
type: Opaque
data:
  postgres-username: ZGV2Zm9yZ2U=
  postgres-password: ZGV2Zm9yZ2U=
  postgres-db: ZGV2Zm9yZ2U=
  rabbitmq-username: cmFiYml0bXE=
  rabbitmq-password: cmFiYml0bXE=
  grafana-admin-password: YWRtaW4=
